#!/bin/bash  
sed -i 's/U_GRID=X/U_GRID=1/g' system_master.f90
sed -i 's/W_GRID=Y/W_GRID=1/g' system_master.f90
sed -i 's/UX_WY/U1_W1/g' makefile
make
sed -i 's/U1_W1/UX_WY/g' makefile
sed -i 's/U_GRID=1/U_GRID=X/g' system_master.f90
sed -i 's/W_GRID=1/W_GRID=Y/g' system_master.f90
cp run_UX_WY.sub run_U1_W1.sub
sed -i 's/UX_WY/U1_W1/g' run_U1_W1.sub
sbatch run_U1_W1.sub
#=================================================
sed -i 's/U_GRID=X/U_GRID=2/g' system_master.f90
sed -i 's/W_GRID=Y/W_GRID=1/g' system_master.f90
sed -i 's/UX_WY/U2_W1/g' makefile
make
sed -i 's/U2_W1/UX_WY/g' makefile
sed -i 's/U_GRID=2/U_GRID=X/g' system_master.f90
sed -i 's/W_GRID=1/W_GRID=Y/g' system_master.f90
cp run_UX_WY.sub run_U2_W1.sub
sed -i 's/UX_WY/U2_W1/g' run_U2_W1.sub
sbatch run_U2_W1.sub
#=================================================
sed -i 's/U_GRID=X/U_GRID=10/g' system_master.f90
sed -i 's/W_GRID=Y/W_GRID=1/g' system_master.f90
sed -i 's/UX_WY/U10_W1/g' makefile
make
sed -i 's/U10_W1/UX_WY/g' makefile
sed -i 's/U_GRID=10/U_GRID=X/g' system_master.f90
sed -i 's/W_GRID=1/W_GRID=Y/g' system_master.f90
cp run_UX_WY.sub run_U10_W1.sub
sed -i 's/UX_WY/U10_W1/g' run_U10_W1.sub
sbatch run_U10_W1.sub
#=================================================
sed -i 's/U_GRID=X/U_GRID=1/g' system_master.f90
sed -i 's/W_GRID=Y/W_GRID=2/g' system_master.f90
sed -i 's/UX_WY/U1_W2/g' makefile
make
sed -i 's/U1_W2/UX_WY/g' makefile
sed -i 's/U_GRID=1/U_GRID=X/g' system_master.f90
sed -i 's/W_GRID=2/W_GRID=Y/g' system_master.f90
cp run_UX_WY.sub run_U1_W2.sub
sed -i 's/UX_WY/U1_W2/g' run_U1_W2.sub
sbatch run_U1_W2.sub
#=================================================
sed -i 's/U_GRID=X/U_GRID=2/g' system_master.f90
sed -i 's/W_GRID=Y/W_GRID=2/g' system_master.f90
sed -i 's/UX_WY/U2_W2/g' makefile
make
sed -i 's/U2_W2/UX_WY/g' makefile
sed -i 's/U_GRID=2/U_GRID=X/g' system_master.f90
sed -i 's/W_GRID=2/W_GRID=Y/g' system_master.f90
cp run_UX_WY.sub run_U2_W2.sub
sed -i 's/UX_WY/U2_W2/g' run_U2_W2.sub
sbatch run_U2_W2.sub
#=================================================
sed -i 's/U_GRID=X/U_GRID=10/g' system_master.f90
sed -i 's/W_GRID=Y/W_GRID=2/g' system_master.f90
sed -i 's/UX_WY/U10_W2/g' makefile
make
sed -i 's/U10_W2/UX_WY/g' makefile
sed -i 's/U_GRID=10/U_GRID=X/g' system_master.f90
sed -i 's/W_GRID=2/W_GRID=Y/g' system_master.f90
cp run_UX_WY.sub run_U10_W2.sub
sed -i 's/UX_WY/U10_W2/g' run_U10_W2.sub
sbatch run_U10_W2.sub
#=================================================
sed -i 's/U_GRID=X/U_GRID=1/g' system_master.f90
sed -i 's/W_GRID=Y/W_GRID=10/g' system_master.f90
sed -i 's/UX_WY/U1_W10/g' makefile
make
sed -i 's/U1_W10/UX_WY/g' makefile
sed -i 's/U_GRID=1/U_GRID=X/g' system_master.f90
sed -i 's/W_GRID=10/W_GRID=Y/g' system_master.f90
cp run_UX_WY.sub run_U1_W10.sub
sed -i 's/UX_WY/U1_W10/g' run_U1_W10.sub
sbatch run_U1_W10.sub
#=================================================
sed -i 's/U_GRID=X/U_GRID=2/g' system_master.f90
sed -i 's/W_GRID=Y/W_GRID=10/g' system_master.f90
sed -i 's/UX_WY/U2_W10/g' makefile
make
sed -i 's/U2_W10/UX_WY/g' makefile
sed -i 's/U_GRID=2/U_GRID=X/g' system_master.f90
sed -i 's/W_GRID=10/W_GRID=Y/g' system_master.f90
cp run_UX_WY.sub run_U2_W10.sub
sed -i 's/UX_WY/U2_W10/g' run_U2_W10.sub
sbatch run_U2_W10.sub
#=================================================
sed -i 's/U_GRID=X/U_GRID=10/g' system_master.f90
sed -i 's/W_GRID=Y/W_GRID=10/g' system_master.f90
sed -i 's/UX_WY/U10_W10/g' makefile
make
sed -i 's/U10_W10/UX_WY/g' makefile
sed -i 's/U_GRID=10/U_GRID=X/g' system_master.f90
sed -i 's/W_GRID=10/W_GRID=Y/g' system_master.f90
cp run_UX_WY.sub run_U10_W10.sub
sed -i 's/UX_WY/U10_W10/g' run_U10_W10.sub
sbatch run_U10_W10.sub
